[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Enable optimizer to fix stack too deep
optimizer = true
optimizer_runs = 200

# Add via-ir for complex contracts
via_ir = false  # Start with false, enable if needed

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }