[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Enable optimizer and via-ir to fix "Stack too deep" errors
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
